"""empty message

Revision ID: 50a40ba93676
Revises: 373aa5bd2023
Create Date: 2025-05-18 14:23:08.143926

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50a40ba93676'
down_revision = '373aa5bd2023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cars',
        'date_from',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        'cars',
        'date_to',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cars',
        'date_to',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        'cars',
        'date_from',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
