"""empty message

Revision ID: 650825f2dd54
Revises:
Create Date: 2025-03-05 15:31:59.642761

"""
import fastapi_storages
import sqlalchemy as sa
from alembic import op
from fastapi_storages.integrations.sqlalchemy import ImageType

from src.settings import get_settings

# revision identifiers, used by Alembic.
revision = '650825f2dd54'
down_revision = None
branch_labels = None
depends_on = None

storage = get_settings().storage


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'brands',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=True)
    op.create_table(
        'car_options',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_options')),
    )
    op.create_index(op.f('ix_car_options_id'), 'car_options', ['id'], unique=True)
    op.create_table(
        'car_models',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('brand_id', sa.UUID(), nullable=False),
        sa.Column('drive', sa.Enum('RWD', 'FWD', 'AWD', name='carmodeldrive'),
                  nullable=False),
        sa.Column('gearbox', sa.Enum('MANUAL', 'AUTOMATIC', 'ROBOT', 'CVT',
                                     name='carmodelgearbox'), nullable=False),
        sa.Column(
            'body',
            sa.Enum(
                'SEDAN',
                'LIFTBACK',
                'COUPE',
                'HATCHBACK_3',
                'HATCHBACK_5',
                'WAGON',
                'SUV_3',
                'SUV_5',
                'MINIVAN',
                'PICKUP',
                'LIMOUSINE',
                'VAN',
                'CABRIOLET',
                name='carmodelbody',
            ),
            nullable=False,
        ),
        sa.Column(
            'fuel', sa.Enum('AI_92', 'AI_95', 'AI_100', 'GAS', 'DIESEL', 'ELECTRO',
                            name='carmodelfuel'), nullable=False
        ),
        sa.Column('fuel_consumption', sa.Numeric(), nullable=False),
        sa.Column('hp', sa.Integer(), nullable=False),
        sa.Column('engine_capacity', sa.Numeric(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['brand_id'], ['brands.id'],
                                name=op.f('fk_car_models_brand_id_brands')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_models')),
    )
    op.create_index(op.f('ix_car_models_id'), 'car_models', ['id'], unique=True)
    op.create_table(
        'cars',
        sa.Column('car_model_id', sa.UUID(), nullable=False),
        sa.Column('color', sa.String(), nullable=False),
        sa.Column('score', sa.Numeric(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('NOT_VERIFIED', 'VERIFIED', 'ARCHIVED', 'BANNED', name='carstatus'),
            nullable=False
        ),
        sa.Column('latitude', sa.String(), nullable=False),
        sa.Column('longitude', sa.String(), nullable=False),
        sa.Column('date_from', sa.DateTime(), nullable=True),
        sa.Column('date_to', sa.DateTime(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'],
                                name=op.f('fk_cars_car_model_id_car_models')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cars')),
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=True)
    op.create_table(
        'car_attachments',
        sa.Column('car_id', sa.UUID(), nullable=False),
        sa.Column('attachment',
                  fastapi_storages.integrations.sqlalchemy.FileType(storage),
                  nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['car_id'], ['cars.id'],
                                name=op.f('fk_car_attachments_car_id_cars')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_attachments')),
    )
    op.create_index(op.f('ix_car_attachments_id'), 'car_attachments', ['id'],
                    unique=True)
    op.create_table(
        'car_options_association',
        sa.Column('car_id', sa.UUID(), nullable=False),
        sa.Column('car_option_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['car_id'], ['cars.id'],
                                name=op.f('fk_car_options_association_car_id_cars')),
        sa.ForeignKeyConstraint(
            ['car_option_id'], ['car_options.id'],
            name=op.f('fk_car_options_association_car_option_id_car_options')
        ),
        sa.PrimaryKeyConstraint('car_id', 'car_option_id',
                                name=op.f('pk_car_options_association')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_options_association')
    op.drop_index(op.f('ix_car_attachments_id'), table_name='car_attachments')
    op.drop_table('car_attachments')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_car_models_id'), table_name='car_models')
    op.drop_table('car_models')
    op.drop_index(op.f('ix_car_options_id'), table_name='car_options')
    op.drop_table('car_options')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
